### PR TITLE
mesh view example

### PR DESCRIPTION
**Pull request by leo-brewin**
Here is a simple example that can display simple triangle meshes (in the .obj format). I'm new to GitHub so if there are things that I've done that don't conform to standard practice please let me know and I'll fix my mistakes.

### CODE REVIEW

**Comment by rogermc2** [comment]
I'm no expert on Git either.
Great to have another contributor.
I'm guessing its OK to merge this into my master.
In the long run it will need to be reviewed by flyx.
Perhaps it might be helpful to open an "issue" in flyx/OpenGLAda to "advertise" this new example.

**Comment by rogermc2** [comment]
Thanks for this contribution Leo,
	From my comments on GitHub you'll gather that I'm not quite sure how to handle it.
If you like, perhaps I could setup a new branch off my master for you to commit into.

Regards,
Roger

**Comment by rogermc2** [comment]
Hello Leo,
	I decided to make a new branch mesh_view_example.
Please, if possible, commit your code to this branch and PR which I will merge ASAP.
Hope this helps,
Roger

**Comment by rogermc2** [comment]
Actually, I have an excellent instruction sheet from flyx concerning git usage.
Unfortunately I can't locate the original e-mail but, if you like, I could copy it and send it to you.

**Comment by rogermc2** [comment]
The other alternative is to make a new branch off your master.
I thought I suggested that but I must have "lost" the comment.
This is from flyx's advice:
>1. update your clone of my repo: git fetch upstream.
>2.create a new branch based on the master branch of my repo:
>git checkout -b mesh_view_example upstream/master
>3. commit your changes to the new branch.
>4 push the new branch to your remote:
>git push origin mesh_view_example.
>5. You should now be able to create a PR from the mesh_view_example branch.
>This way, you do not EVER commit to the master branch of your fork. This is important for our versions to not converge.

**Comment by rogermc2** [comment]
I'm not sure that even this is the right approach unless I can pass a PR from you onto the flyx repo.
The problem is that if I merge a PR from you then it will merge into my master which would violate the "don't EVER commit to my master branch" rule.
If passing the PR on to the flyx master is not possible an alternative solution may be for you to fork my mesh_view_example then  PR on this would merge your forked branch into my mesh_view_example branch. I could then PR flyx master when appropriate.
I remain unsure of the best solution.
Another "simplest" solution would be for you to fork flyx/OpenGL then create a mesh_view_example on your forked master. But that would tend to put the review onus directly onto flyx rather providing me the opportunity for a preliminary review thus, hopefully, reducing the review effort required from flyx. An advantage is that I am aware of many of flyx's preferences and we could at least fix these prior to bothering him.
I imagine there's a simple solution not obvious to us git novices!

**Comment by rogermc2** [comment]
I've just had a quick look at your code and doubt that I can offer much in the way of review comments so, it seems to me that the best solution would be to fork flyx/OpenGL then create a mesh_view_example on your forked master.
Based on all of my comments the final solution is yours which I'll be happy to support.

**Comment by rogermc2** [comment]
flyx has asked not to submit any more PRs until he has set up a new development branch.

**Comment by leo-brewin** [comment]
Hi Roger,

Thanks for the e-mails.
I'm currently reading through tutorials on git to make some sense of the
multitude of workflows that seem possible. I'm still finding my feet, so
please bear with me if I seem to ask silly questions are do silly things
 (not intentionally but more out of ignorance).

Yesterday I did the following.
1. On my GitHub page I forked your master of OpenGLAda.
2. On my desktop I did a git pull from my GitHub page.
3. I made local edits of the local files.
4. I pushed those edits back to my master on GitHub.
5. I sent a pull request from my GitHub to you.

That's as far as I've got. Now comes the problem (as you've noted). Here ar
few of my current questions:
1. How do I update my GitHub master to keep in step with yours?
2. You mentioned never committing to the master. So that means creating a
branch. Do I do that from your master or from mine.
3. Should I start again by first deleting my master, then re-forking yours
and then create a branch (all in GitHub)?
3. Am I right in assuming that the GitHub web pages are we we exchange our
files?
5. I'm very comfortable with the command line and really would prefer to do
as much Git stuff from there. But I guess I'll have to click some buttons
on the GitHub pages.

You mentioned that you had a great summary of git commands from Felix. If
you could find those that would be a great help.

I'm not planning on making any significant changes to the mesh viewer but
I'm very happy to clean it up and make it ready for anybody else who want
it. So my investment in git will probably be just for this project (I'm not
a developer). I wrote the mesh viewer as bit of fun and its something I use
in my work (maths at Monash Uni).

I did send the code as a tgz archive to Felix some weeks ago and he
suggested it was better for all of us if I went down the git road. He also
suggested that I should include a copyright notice in each file. At present
I've only gone as far as placing a COPYING file in the main directory.

Sorry for the long ramble. On a final note, you're the only other person in
Australia that I know of who codes in Ada (but I'm suer there are others).
I do my best to convince my colleagues that it's (in my opinion) hands down
the best language around for scientific computing (my research is black
holes). But my advice falls of deaf ears -- they prefer the old Fortran
codes and their bug ridden C and C++ codes.

Cheers,
Leo

**Comment by rogermc2** [comment]
I'll respond to your message in separate comments for each section.
"I'm currently reading through tutorials on git to make some sense of the
multitude of workflows that seem possible. "
Yes I find git a real headache.
I originally got into a real mess using the GUI app and decided that was best avoided.
I'm not a command line fan, but for git I find it the only reliable method.
My current method involves using a set of instructions provide by flyx which I intend to provide you with a complete copy tomorrow.
My next line of action is to google operations that I need. I can usually find good instructions this way.
I do have the Progit book which is quite good. In fact I have two copies, so if you give me your address I could send you one. I thin there's a website that provides it only that I used to find fairly good.

**Comment by rogermc2** [comment]
I'll slot in comments based on  my flyx instruction sheet:
"Yesterday I did the following.
1. On my GitHub page I forked your master of OpenGLAda.
This your leo-brewin/OpenGLAda (remote) repository
2. On my desktop I did a git pull from my GitHub page.
According to flyx, you should have a clone of the remote repository on your desktop generated using git clone git@github.com:leo-brewin/OpenGLAda.git. But perhaps you've achieved this another way?
By cloning from your GitHub repository, git will automatically setup a remote called origin which points to your GitHub repository. Flyx provides a lot more detail which I hope to provide tomorrow.
3. I made local edits of the local files.
4. I pushed those edits back to my master on GitHub.
This is where I think you went wrong. You should have created a new branch based on the master branch of my repo. then added, committed and pushed those edits to the new branch using git push origin <new branch>.
5. I sent a pull request from my GitHub to you."
I'm not sure what happened to that PR which I did accept then revert yesterday. The PR itself seems to have disappeared.
I note the situation at present is that your mesh_view is in your master but not in mine.
I think it should be in a separate branch off your (or my master).
Hopefully the flyx instructions will help you sort this out tomorrow.

**Comment by rogermc2** [comment]
Here are few of my current questions:
1. How do I update my GitHub master to keep in step with yours?
This will be covered in the  flux document.
2. You mentioned never committing to the master. So that means creating a
branch. Do I do that from your master or from mine.
The Flyx instruction says do it from mine.
3. Should I start again by first deleting my master, then re-forking yours
and then create a branch (all in GitHub)?
This is probably what I would do (in fact I'd almost say "its the story of my life - make a mess, wipe it up, repeat n times, make a fixable mess then keep cleaning until I'm satisfied.)
But, probably best wait for the Flyx instructions before taking further action.
3. Am I right in assuming that the GitHub web pages are where we we exchange our
files?
I'm not sure if this is the right description. As I understand it files are exchanged between repositories; the web pages probably provide a mechanism for doing this.
5. I'm very comfortable with the command line and really would prefer to do
as much Git stuff from there. But I guess I'll have to click some buttons
on the GitHub pages.
I find I mostly operate via the command line (say 99%) and occassionallly get to click buttons.

OK, first job for me tomorrow is send you that "great summary of git commands from Felix"!
After that I plan to comment on the rest of your message.

**Comment by rogermc2** [comment]
Actually, I think you should be forking off flyx/OpenGLAda.

**Pull request merged**
